version: '3.8'

services:
  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
      - mysql
    networks:
      - petclinic-network

  api-gateway:
    image: orion/api-gateway:1.0
    ports:
      - "10100:8080"
    environment:
    profiles:
    networks:
      - petclinic-network

  petclinic:
    image: orion/petclinic:1.0
    ports:
      - "10200:8080"
    environment:
    profiles:
    networks:
      - petclinic-network

  auth-service:
    image: orion/auth-service:1.0
    ports:
      - "10200:8080"
    environment:
    profiles:
    networks:
      - petclinic-network

  grafana:
    image: orion/grafana:1.0
    ports:
      - "10300:3000"
    environment:
    profiles:
    networks:
      - petclinic-network

  prometheus:
    image: orion/prometheus:1.0
    ports:
      - "10300:3000"
    environment:
    profiles:
    networks:
      - petclinic-network

networks:
  petclinic-network:
    driver: bridge
