version: '3.8'

services:
  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
      - mysql
    networks:
      - petclinic-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 10100:8080
    volumes:
      - ./config/api-gateway/application.yml:/var/opt/application.yml
    environment:
      - SPRING_CONFIG_LOCATION=/var/opt/application.yml
    networks:
      - petclinic-network

  petclinic:
    build:
      context: ./petclinic
      dockerfile: Dockerfile
    networks:
      - petclinic-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    networks:
      - petclinic-network

  grafana:
    build:
      context: ./analytics/grafana
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - ./config/grafana/all.yml:/etc/grafana/provisioning/datasources/all.yml
    networks:
      - petclinic-network

  prometheus:
    build:
      context: ./analytics/prometheus
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - petclinic-network

networks:
  petclinic-network:
    driver: bridge
