name: CI/CD Pipeline

on:
  push:
    branches:
      - dockerhub-test
  pull_request:
    branches:
      - dockerhub-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Analytics Docker image
        run: docker build -t analytics ./analytics

      - name: Build API Gateway Docker image
        run: docker build -t api-gateway ./api-gateway

      - name: Build Auth Service Docker image
        run: docker build -t auth-service ./auth-service

      - name: Build PetClinic Docker image
        run: docker build -t petclinic ./petclinic

  # Rollback if build fails
  rollback:
    runs-on: ubuntu-latest
    needs: build
    if: failure()

    steps:
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Rollback to previous version
      - name: Rollback to previous Docker image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:previous
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:previous ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
