name: Docker Compose Demo

on:
  push:
    branches:
      - main

jobs:
  compose-up:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Sourcery Action
        uses: sourcery-ai/action@v1
        with:
          token: ${{ secrets.SOURCERY_TOKEN }}

      - name: Set up Docker Compose
        run: |
          git submodule init
          git submodule update
          git submodule update --recursive --remote
          docker compose down
          docker compose up -d