name: Docker Compose Demo

on:
  push:
    branches:
      - main
      - ai-code-review

jobs:
  compose-up:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          git submodule init
          git submodule update
          git submodule update --recursive --remote
          docker compose down
          docker compose up -d

      # AI Code Review Action - Kod inceleme işlemi
      - name: AI Code Review Action
        uses: freeedcom/ai-codereviewer@v2.7.0
        with:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
          #OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-3.5-turbo" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas

      # Docker Hub'a Giriş Yapma
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Docker Hub kullanıcı adı
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  # Docker Hub şifresi

      # Docker imajını oluştur ve Docker Hub'a push et
      - name: Build and Push Docker image
        run: |
          docker build -t altokgoz/deploy:latest .
          docker push altokgoz/deploy:latest
